### ISSUE TITLE
Other Data Formats?

### ISSUE THREAD

**Issue by paul-l-smith** [CSSEGISandData/COVID-19_Unified-Dataset#4]
Is the COVID=19_Unified_Dataset available in other formats such as csv?
(We aren't allowed to install R on our server)

**Comment by hsbadr** [comment]
The dataset was initially available in other formats (e.g., compressed CSV), but the files are much larger in size. I think that `rds` format can be easily imported in Python (e.g., by using `pyreadr.read_r`).

**Comment by wez378** [comment]
open

**Comment by drsect0r** [comment]
+1 for different file formats.

I'd like to use this dataset within the Golang language and it seems that not all programming languages have the capabilities to read RDS files. Would compressed CSV files be an idea?

**Comment by drsect0r** [comment]
@hsbadr Thank you! :) Would the Hydromet data be included in the next update?

**Comment by hsbadr** [comment]
You're welcome. The hydromet data will get very big in CSV format, even if highly compressed. But, I'll check if it can be split to be under 100MB per file.

**Comment by drsect0r** [comment]
@hsbadr Thank you again. :)
