### ISSUE TITLE
COVID-19_Static.rds potential problems for some variables

### ISSUE THREAD

**Issue by fabnavarro** [CSSEGISandData/COVID-19_Unified-Dataset#9]
Dear Hamada Bard,

Thanks a lot for this great repo!

I am working on the COVID-19_Static.md table (in the COVID-19_Unified-Dataset folder) and I am confused about the values taken by the `Hypertension` variable. The values are between 0 and 100 for US states (e.g., Id="US01") but not for EU countries (e.g., ID="AT") where the values are above 100 million, i.e.
```r
df<-readRDS("COVID-19_Static.rds")
summary(df$Hypertension)
#>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.      NA's 
#>2.600e+01 3.400e+01 5.436e+07 6.031e+08 3.082e+08 3.310e+10     16126
```

I am also confused about some of the `WorldPop_` variables, especially for US states like Alaska (US02). For this state, `WorldPop_65` is zero and `WorldPop` is 3.

Finally, I have a question about the calculation of the `COPD`, `CVD`, and `HIV` variables from their measurements on the Male and Female population. It seems that the Total for each variable is not obtained as a weighted sum between the measurements recorded on the male and female population. Could you please give me some details on the calculation?

Again, thank you very much for your work.

I am looking forward to hearing from you.

Best,
Fabien

**Comment by hsbadr** [comment]
@fabnavarro Thank you for opening this issue. The `Hypertension` values should be in the 0-100 range, but there's a bug where in a subset of the data we didn't divide by the total population.  Also, the `WorldPop_` variables seem to be mistakenly rounded.

As for the equation, it's a simple weighted average, which is affected by the population issue.

 I'll fix those issues in the next update.

**Comment by fabnavarro** [comment]
@hsbadr Thanks a lot!

**Comment by hsbadr** [comment]
Thank you for reporting those issues. Please check the current version and let me know it you run into similar issues.

**Comment by fabnavarro** [comment]
@hsbadr Thank you very much, the three points raised in my previous message are now ok.

I noticed one last concern regarding the observations associated with the US. Indeed, they are duplicated and differ slightly from one row to another for some variables, e.g., 
```r
df[which(df$ID=="US01"),]
#># A tibble: 2 x 34
#>  ID    PM2.5 PM2.5_PopWtd   NO2 NO2_PopWtd Access_City Access_Motor
#>  <chr> <dbl>        <dbl> <dbl>      <dbl>       <dbl>        <dbl>
#>1 US01   8.33         8.53  2.90       5.55        55.6         16.6
#>2 US01   8.33         8.47  2.91       5.35        55.6         16.6
```

**Comment by hsbadr** [comment]
> they are duplicated and differ slightly

Ah! I see. This is due an old air quality tables that should've been removed. I'll fix it now. Thanks!

**Comment by fabnavarro** [comment]
Thank you!
I think that the deletion of the redundant line from the old table, has generated NA for US11, indeed, I just realized (by making a matching) that the latter had no duplication unlike the other US *.

**Comment by hsbadr** [comment]
> has generated NA for US11

It seems that DC isn't processed in the updated AQ estimates; I'll forward this to the team.

**Comment by fabnavarro** [comment]
Thank you very much!
